### ISSUE TITLE
Specify license

### ISSUE THREAD

**Issue by alufers** [IFOSSA/inpost-python#57]
**Is your feature request related to a problem? Please describe.**

The library does not specify any license, due to copyright laws it cannot be used by anybody. I am not sure if it is intended.

**Describe the solution you'd like**

Specify a license such as MIT, Apache, BSD or GPL. The license should be specified in `pyproject.toml` and as a LICENSE.md file, so that pypi and Github can pick it up.

**Comment by loboda4450** [comment]
Hello,

thank you for reminding me about license :see_no_evil: . It will come up in a second.
